[build]
command = "pnpm --filter @org/generic build"
publish = "public"
edge_functions = "edge-functions"

[functions]
node_bundler = "esbuild"

[[edge_functions]]
function = "test_worker"
path = "/*"